[package]
name = "KYClessEnrollment"
version = "1.0.0"
authors = []

[addresses]
MyModule = "0x363e7fba80d0af88f33970454d96cee79bf06bd85915f5422709b6b431d07f01"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]